apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/weaveworks/podify
  version:
    semver: v1.0.3-dev
  repository:
    url: ghcr.io/skarlso/ocm-podify
    secretRef:
      name: oci-creds
  verify: []
  references:
    expand: true
